cnpg-cluster:
  # Default values for cnpg-cluster with backup.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  logLevel: info
  instances: 1

  image:
    repository: ghcr.io/cloudnative-pg/postgresql
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "17.0"

  storage:
    storageClass: 
    size: 2Gi
  walStorage:
    storageClass: 
    size: 2Gi

  postgresql:
    parameters:
      # Parameter max_wal_size (default 1GB) should be smaller than WAL volume size    
      max_wal_size: "1GB"
      max_wal_senders: "16"
      wal_keep_size: "128MB"
      fsync: "on"
      log_connections: "false"
      log_disconnections: "false"
      log_hostname: "false"
      checkpoint_timeout: "5min" 

  disaster_recovery: false
  point_in_time_recovery: false

  backup:
    enabled: true
    destinationPath: "test"
    serverName: "" 
    # googleCredentials:
    #   gkeEnvironment:
    #   applicationCredentials:
    # s3Credentials:
    #   accessKeyId:
    #   secretAccessKey:
    #   region:    
    azureCredentials:
      connectionString:
        name: azure-creds
        key: AZURE_BLOB_STRING
    wal:
      compression: gzip
    data:
      compression: gzip
      immediateCheckpoint: true
      jobs: 2
    retentionPolicy: "14d"

  scheduledBackups:
    suspend: false
    immediate: true
    schedule: "0 0 0 * * *" # Daily at midnight

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"

  pooler:
    instances: 1
    type: rw
    resources:
      requests:
        cpu: "0.1"
        memory: 100Mi
      limits:
        cpu: "0.5"
        memory: 500Mi

    pgbouncer:
      poolMode: session
      parameters:
        max_client_conn: "1000"
        default_pool_size: "10"

  monitoring:
    enablePodMonitor: true