{{ if .Values.backup.enabled}}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "cnpg-cluster.fullname" . }}
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "cnpg-cluster.labels" . | nindent 4 }}

spec:
  # Note that this cron dialect has 6 places - an additional one for seconds
  schedule: {{ .Values.scheduledBackups.schedule }} 

  # Set this to true, if you want to suspend the backup for now
  suspend: {{ .Values.scheduledBackups.suspend }}
  
  # Determines if the first backup should be done immediately
  immediate: {{ .Values.scheduledBackups.immediate }}
  
  #Indicates which ownerReference should be put inside the created backup resources.
  # - none: no owner reference for created backup objects (same behavior as before the field was introduced)
  # - self: sets the Scheduled backup object as owner of the backup
  # - cluster: set the cluster as owner of the backup
  backupOwnerReference: self
  cluster:
    name: {{ include "cnpg-cluster.fullname" . }}
{{ end }}