apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi-cnpg
parameters:
  skuname: StandardSSD_LRS
provisioner: disk.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
